"""Shared fixtures: graph copies, scripted command/browser runners, and a generated-project factory.

The real `projects/task_manager/graphs` package is the golden input; negative tests copy it and break one thing.
"""
from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

import pytest

from app.config.settings import Limits, Settings
from app.execution.browser_runner import BrowserRunner, BrowserRunResult, TestOutcome
from app.execution.command_runner import Cmd, CommandResult, CommandRunner
from app.llm.mock import MockLLMProvider
from app.pipeline.orchestrator import FrontendAgent

REPO = Path(__file__).resolve().parents[1]
TASK_MANAGER = REPO / "projects" / "task_manager"


@pytest.fixture()
def project(tmp_path: Path) -> Path:
    """A writable copy of the task_manager project (graphs only)."""
    dst = tmp_path / "task_manager"
    shutil.copytree(TASK_MANAGER / "graphs", dst / "graphs")
    return dst


def edit_graph(project: Path, name: str, fn: Callable[[list[dict]], None]) -> None:
    path = project / "graphs" / f"{name}.json"
    data = json.loads(path.read_text())
    fn(data["nodes"])
    path.write_text(json.dumps(data, indent=2))


def node(nodes: list[dict], ref: str) -> dict:
    return next(n for n in nodes if n["id"] == ref)


# ----------------------------------------------------------------------------- scripted tool runners
@dataclass
class ScriptedCommands(CommandRunner):
    """Returns canned results per command; unlisted commands succeed. Records every call."""

    script: dict[Cmd, list[CommandResult]] = field(default_factory=dict)
    calls: list[Cmd] = field(default_factory=list)

    def run(self, cmd: Cmd, cwd: Path, env: dict[str, str] | None = None) -> CommandResult:
        self.calls.append(cmd)
        queue = self.script.get(cmd)
        if queue:
            return queue.pop(0) if len(queue) > 1 else queue[0]
        return CommandResult(cmd, 0, "ok")

    def count(self, cmd: Cmd) -> int:
        return self.calls.count(cmd)


def failing(cmd: Cmd, output: str) -> CommandResult:
    return CommandResult(cmd, 1, output)


def passing(cmd: Cmd) -> CommandResult:
    return CommandResult(cmd, 0, "ok")


def outcome(title: str, status: str = "passed", error: str = "", file: str = "tests/e2e/x.spec.ts") -> TestOutcome:
    return TestOutcome(title, file, status, error)


@dataclass
class ScriptedBrowser(BrowserRunner):
    e2e: list[BrowserRunResult] = field(default_factory=lambda: [BrowserRunResult(None, [outcome("ok")])])
    visual: list[Callable[[Path], BrowserRunResult]] = field(default_factory=list)
    e2e_calls: int = 0
    visual_calls: int = 0

    def run_e2e(self, cwd: Path) -> BrowserRunResult:
        self.e2e_calls += 1
        return self.e2e.pop(0) if len(self.e2e) > 1 else self.e2e[0]

    def run_visual(self, cwd: Path, screenshot_dir: Path) -> BrowserRunResult:
        self.visual_calls += 1
        fn = self.visual.pop(0) if len(self.visual) > 1 else self.visual[0]
        return fn(screenshot_dir)


def write_capture(shot_dir: Path, screen: str, viewport: str, **metric_overrides) -> None:
    metrics = {
        "viewport": {"width": {"desktop": 1280, "tablet": 820, "mobile": 390}[viewport], "height": 800}, "horizontalOverflow": False, "documentWidth": 390,
        "overflowingElements": [], "clippedText": [], "smallTargets": [], "overlappingControls": [], "h1Count": 1, "mainTextLength": 50, "mainHeight": 400, "dialog": None, "tables": [],
    }
    metrics.update(metric_overrides)
    shot_dir.mkdir(parents=True, exist_ok=True)
    (shot_dir / f"{screen}__{viewport}.png").write_bytes(b"\x89PNG\r\n")
    (shot_dir / f"{screen}__{viewport}.json").write_text(json.dumps({"screen": screen, "viewport": viewport, "route": "/", "metrics": metrics}))


# ----------------------------------------------------------------------------- agent factory
def make_agent(project: Path, llm=None, commands=None, browser=None, limits: Limits | None = None, **kw) -> FrontendAgent:
    settings = Settings(limits=limits or Limits())
    return FrontendAgent(project, llm or MockLLMProvider(), settings=settings, commands=commands or ScriptedCommands(), browser=browser or ScriptedBrowser(), **kw)


@pytest.fixture()
def generated(project: Path) -> FrontendAgent:
    """An agent whose pipeline ran up to GENERATED (no npm needed): planning + all code generated by the mock LLM."""
    agent = make_agent(project)
    agent._prepare_workspace()
    agent.plan_and_generate()
    return agent
