"""Deterministic generation: scaffold, design primitives and every module that is a pure function of the graph.

Anything here is generated by Python, never by the LLM: types, zod schemas, API clients, permission tables,
state-machine tables, routes, navigation and the e2e mock-API data.  The LLM only writes feature code and tests
*on top of* these contracts (see the code_generation stage).
"""
from __future__ import annotations

import json
from pathlib import Path

from app.domain.models.graph import GraphPackage
from app.domain.models.naming import camel, pascal, slug
from app.domain.specifications.specs import FileRecord, ScreenSpec
from app.generation.file_generator import FileWorkspace
from app.generation.symbols import (
    ApiBinding, build_api_bindings, collection_of, enum_type_name, entity_name, field_label, import_path, seed_data,
    ts_field_type, workflow_schema_file, workflow_schema_names,
)
from app.validation.permission_validation import role_permissions

TEMPLATES = Path(__file__).parent / "templates" / "frontend"
HEADER = "// Generated from the project graph by the Frontend Agent. Do not edit by hand; regenerate instead.\n"


def ts_json(obj) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False)


def find_user_entity(g: GraphPackage) -> dict | None:
    return next((e for e in g.entities if {"email", "role", "name", "id"} <= {f["name"] for f in e["fields"]}), None)


class ProjectGenerator:
    def __init__(self, g: GraphPackage, ws: FileWorkspace):
        self.g = g
        self.ws = ws
        self.bindings: list[ApiBinding] = build_api_bindings(g)
        self.records: list[FileRecord] = []
        self.user_entity = find_user_entity(g)

    # ------------------------------------------------------------------ helpers
    def _emit(self, path: str, content: str, purpose: str, refs: list[str] | None = None, generator: str = "graph") -> None:
        self.ws.write(path, content)
        self.records.append(FileRecord(path=path, purpose=purpose, source_refs=sorted(set(refs or [])), generator=generator, digest=self.ws.digest(content)))

    def _project_node(self) -> dict:
        return self.g.nodes("project")[0]

    # ------------------------------------------------------------------ scaffold
    def write_scaffold(self) -> None:
        proj = self._project_node()
        pkg = slug(self.g.project_id.replace("_", "-")) or "frontend"
        subs = {"__PACKAGE_NAME__": f"{pkg}-frontend", "__TITLE__": proj["name"], "__SESSION_KEY__": f"{self.g.project_id}.session"}
        for src in sorted(TEMPLATES.rglob("*")):
            if not src.is_file():
                continue
            rel = src.relative_to(TEMPLATES).as_posix()
            text = src.read_text(encoding="utf-8")
            if rel.endswith(".tmpl"):
                rel = rel[: -len(".tmpl")]
                for k, v in subs.items():
                    text = text.replace(k, v)
            self._emit(rel, text, f"Static scaffold: {rel}", [proj["id"]], generator="template")

    def write_design_system(self, ds: dict) -> None:
        colors = ds["colors"]
        cfg = f"""import type {{ Config }} from 'tailwindcss';

// Tokens come from frontend-artifacts/design_system.json
const colors = {ts_json(colors)};

export default {{
  content: ['./index.html', './src/**/*.{{ts,tsx}}'],
  theme: {{
    extend: {{
      colors,
      fontFamily: {{ sans: {ts_json(ds['typography']['fontFamily']['sans'])} }},
      borderRadius: {{ DEFAULT: '{ds['radius']['md']}', sm: '{ds['radius']['sm']}', md: '{ds['radius']['md']}', lg: '{ds['radius']['lg']}', xl: '{ds['radius']['xl']}' }},
      boxShadow: {{ card: '{ds['shadows']['card']}', dialog: '{ds['shadows']['dialog']}' }},
    }},
  }},
  plugins: [],
}} satisfies Config;
"""
        self._emit("tailwind.config.ts", cfg, "Tailwind theme generated from the design-system tokens", [], "template")
        css = f"""@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {{
  html {{
    -webkit-text-size-adjust: 100%;
  }}
  body {{
    @apply bg-background font-sans text-text antialiased;
    font-size: {ds['typography']['scale']['base']};
    line-height: 1.5;
  }}
  :focus-visible {{
    outline: 2px solid {colors['focusRing']};
    outline-offset: 2px;
  }}
  a {{
    @apply text-primary;
  }}
}}

@media (prefers-reduced-motion: reduce) {{
  *, *::before, *::after {{
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
  }}
}}
"""
        self._emit("src/index.css", css, "Global styles from design-system tokens", [], "template")

    # ------------------------------------------------------------------ graph modules
    def write_graph_modules(self, screen_specs: list[ScreenSpec]) -> None:
        self._write_types()
        self._write_validation()
        self._write_api()
        self._write_permissions()
        self._write_state_machines()
        self._write_routes(screen_specs)
        self._write_e2e_data()

    def _entity_interface(self, e: dict) -> str:
        eref = e["id"]
        lines = [HEADER, f"// Source: {eref}\n"]
        for f in e["fields"]:
            if f["type"] == "enum":
                const = f"{slug(eref).upper().replace('-', '_')}_{f['name'].upper()}_VALUES"
                vals = ", ".join(f"'{v}'" for v in f["values"])
                lines.append(f"export const {const} = [{vals}] as const;")
                lines.append(f"export type {enum_type_name(eref, f['name'])} = (typeof {const})[number];\n")
        lines.append(f"export interface {entity_name(eref)} {{")
        for f in e["fields"]:
            opt = "" if f.get("required") else "?"
            ty = ts_field_type(self.g, eref, f) + ("" if f.get("required") else " | null")
            lines.append(f"  {f['name']}{opt}: {ty};")
        lines.append("}\n")
        for b in self.bindings:
            if b.request_entity_ref != eref:
                continue
            if b.input_type:
                lines.append(f"/** Request body of {b.id} */\nexport interface {b.input_type} {{")
                for f in b.body_fields:
                    ef = self.g.entity_field(eref, f["name"]) or {}
                    ty = ts_field_type(self.g, eref, {**f, **{k: ef[k] for k in ("values",) if k in ef}})
                    lines.append(f"  {f['name']}{'' if f.get('required') else '?'}: {ty};")
                lines.append("}\n")
            if b.params_type:
                lines.append(f"/** Query parameters of {b.id} */\nexport interface {b.params_type} {{")
                for f in b.query_fields:
                    lines.append(f"  {f['name']}?: string;")
                lines.append("}\n")
        return "\n".join(lines)

    def _write_types(self) -> None:
        for e in self.g.entities:
            refs = [e["id"]] + [b.id for b in self.bindings if b.request_entity_ref == e["id"]]
            self._emit(f"src/types/{slug(e['id'])}.ts", self._entity_interface(e), f"TypeScript types for {e['id']}", refs)
        user_import = ""
        user_t = "{ id: string; name: string; role: string }"
        if self.user_entity:
            user_import = f"import type {{ {entity_name(self.user_entity['id'])} }} from './{slug(self.user_entity['id'])}';\n\n"
            user_t = entity_name(self.user_entity["id"])
        login = next((b for b in self.bindings if b.operation == "login"), None)
        content = HEADER + user_import + f"export type AuthUser = {user_t};\n\nexport interface Session {{\n  token: string;\n  user: AuthUser;\n}}\n"
        self._emit("src/types/api.ts", content, "Shared API types (session)", [login.id] if login else [])

    def _zod_field(self, entity_ref: str, name: str) -> str:
        f = self.g.entity_field(entity_ref, name) or {"type": "string"}
        label = field_label(self.g, entity_ref, name)
        rules: dict = {}
        msgs: list[str] = []
        for v in self.g.validations_for(entity_ref, name):
            rules.update(v["rules"])
            if v.get("message"):
                msgs.append(v["message"])
        required = bool(f.get("required") or rules.get("required"))
        custom = msgs[0] if msgs else None
        t = f["type"]
        base = "z.string()" if t in ("password", "enum", "ref", "date", "datetime") else "z.string().trim()"
        if t in ("integer", "number"):
            base = "z.coerce.number()"
        chain = [base]
        if required and t not in ("integer", "number"):
            chain.append(".min(1, %s)" % json.dumps(custom or f"{label} is required"))
        if rules.get("min_length"):
            n = rules["min_length"]
            chain.append(".min(%d, %s)" % (n, json.dumps(f"{label} must be at least {n} characters")))
        if rules.get("max_length"):
            n = rules["max_length"]
            chain.append(".max(%d, %s)" % (n, json.dumps(f"{label} must be at most {n} characters")))
        if rules.get("format") == "email" or t == "email":
            chain.append(".email('Enter a valid email address')")
        if rules.get("pattern"):
            chain.append(".regex(new RegExp(%s), %s)" % (json.dumps(rules["pattern"]), json.dumps(custom or f"{label} has an invalid format")))
        if t == "date":
            chain.append(".regex(/^\\d{4}-\\d{2}-\\d{2}$/, 'Enter a valid date')")
        if t == "enum" and f.get("values"):
            vals = ", ".join(f"'{v}'" for v in f["values"])
            chain.append(".refine((v) => [%s].includes(v), { message: %s })" % (vals, json.dumps(f"Select a valid {label.lower()}")))
        expr = "".join(chain)
        if not required:
            expr = f"{expr}.optional().or(z.literal(''))" if t not in ("integer", "number") else f"{expr}.optional()"
        return expr

    def _write_validation(self) -> None:
        for wf in self.g.workflows:
            if not wf.get("form_fields"):
                continue
            schema, values, defaults = workflow_schema_names(wf)
            lines = [HEADER, f"// Source: {wf['id']} / {wf['entity']} / validations.json\n", "import { z } from 'zod';\n", f"export const {schema} = z.object({{"]
            for name in wf["form_fields"]:
                lines.append(f"  {name}: {self._zod_field(wf['entity'], name)},")
            lines.append("});\n")
            lines.append(f"export type {values} = z.infer<typeof {schema}>;\n")
            lines.append(f"export const {defaults}: {values} = {{")
            for name in wf["form_fields"]:
                f = self.g.entity_field(wf["entity"], name) or {}
                lines.append(f"  {name}: {'0' if f.get('type') in ('integer', 'number') else repr('')},")
            lines.append("};")
            refs = [wf["id"], wf["entity"]] + [v["id"] for n in wf["form_fields"] for v in self.g.validations_for(wf["entity"], n)]
            self._emit(workflow_schema_file(wf), "\n".join(lines).replace("'', ", "'', ") + "\n", f"Zod schema for {wf['id']}", refs)

    def _write_api(self) -> None:
        by_res: dict[str, list[ApiBinding]] = {}
        for b in self.bindings:
            by_res.setdefault(b.resource, []).append(b)
        for res, bs in by_res.items():
            type_imports: dict[str, set[str]] = {}
            needs_session = any(b.session_fields for b in bs)
            body: list[str] = []
            for b in bs:
                if b.shape == "session":
                    type_imports.setdefault("api", set()).add("Session")
                elif b.entity_ref:
                    type_imports.setdefault(slug(b.entity_ref), set()).add(b.entity)
                if b.input_type:
                    type_imports.setdefault(slug(b.request_entity_ref), set()).add(b.input_type)
                if b.params_type:
                    type_imports.setdefault(slug(b.request_entity_ref), set()).add(b.params_type)
                args = [f"{p}: string" for p in b.path_params]
                if b.input_type:
                    args.append(f"input: {b.input_type}")
                if b.params_type:
                    args.append(f"params?: {b.params_type}")
                if b.method == "GET":
                    args.append("signal?: AbortSignal")
                path = b.path
                for p in b.path_params:
                    path = path.replace("{" + p + "}", "${encodeURIComponent(" + p + ")}")
                path_lit = f"`{path}`" if b.path_params else f"'{path}'"
                opts = [f"method: '{b.method}'", f"path: {path_lit}"]
                if b.params_type:
                    opts.append("query: params")
                if b.input_type or b.session_fields:
                    items = [f"{f['name']}: input.{f['name']}" for f in b.body_fields]
                    for f in b.session_fields:
                        attr = "id" if f["source"] == "session.user_id" else "role"
                        items.append(f"{f['name']}: getSession()?.user.{attr}")
                    opts.append(f"body: compact({{ {', '.join(items)} }})" if not (b.input_type and not b.session_fields and b.operation == "login") else "body: input")
                if b.method == "GET":
                    opts.append("signal")
                if not b.api.get("auth", True):
                    opts.append("auth: false")
                body.append(
                    f"/** {b.id}: {b.method} {b.path} */\nexport function {b.function}({', '.join(args)}): Promise<{b.returns_ts}> {{\n"
                    f"  return request<{b.returns_ts}>({{ {', '.join(opts)} }});\n}}\n"
                )
            imports = ["import { compact, request } from './client';"]
            if needs_session:
                imports.append("import { getSession } from '../auth/session';")
            for mod, names in sorted(type_imports.items()):
                imports.append(f"import type {{ {', '.join(sorted(names))} }} from '../../types/{mod}';")
            content = HEADER + "\n".join(imports) + "\n\n" + "\n".join(body)
            if not any("compact(" in x for x in body):
                content = content.replace("import { compact, request }", "import { request }")
            self._emit(f"src/lib/api/{res}.ts", content, f"API client for {res} (from api.json)", [b.id for b in bs] + [b.entity_ref for b in bs if b.entity_ref])

    def _write_permissions(self) -> None:
        rp = role_permissions(self.g)
        perm_ids = [p["id"] for p in self.g.permissions]
        conds: dict[str, dict] = {}
        role_key = {r["id"]: r["key"] for r in self.g.roles}
        for p in self.g.permissions:
            for rid, c in (p.get("conditions") or {}).items():
                conds.setdefault(p["id"], {})[role_key[rid]] = c
        content = f"""{HEADER}
export type PermissionId = {' | '.join(repr(p) for p in perm_ids)};

export const PERMISSIONS: readonly PermissionId[] = {ts_json(perm_ids)};

/** role key -> permissions the graph grants it (permissions.json / roles.json) */
export const ROLE_PERMISSIONS: Record<string, readonly PermissionId[]> = {ts_json({k: sorted(v) for k, v in rp.items()})};

/** Row-level conditions, e.g. employees may only act on tasks assigned to them. */
const CONDITIONS: Partial<Record<PermissionId, Record<string, {{ scope: string; field: string }}>>> = {ts_json(conds)};

interface Actor {{
  id: string;
  role: string;
}}

/**
 * UI-level permission check. This only decides what the interface shows; the backend enforces authorization.
 * Without a `resource`, conditional permissions are granted (coarse check, e.g. for navigation).
 */
export function can(user: Actor | null | undefined, permission: PermissionId, resource?: object | null): boolean {{
  if (!user) return false;
  if (!(ROLE_PERMISSIONS[user.role] ?? []).includes(permission)) return false;
  const cond = CONDITIONS[permission]?.[user.role];
  if (!cond || !resource) return true;
  return (resource as Record<string, unknown>)[cond.field] === user.id;
}}
"""
        self._emit("src/lib/permissions.ts", content, "Permission table from permissions.json / roles.json", perm_ids + [r["id"] for r in self.g.roles])

    def _write_state_machines(self) -> None:
        machines = {sm["id"]: {"entity": sm["entity"], "field": sm["field"], "initial": sm["initial"], "states": sm["states"],
                               "transitions": [{"from": t["from"], "to": t["to"], "permission": t.get("permission")} for t in sm["transitions"]]}
                    for sm in self.g.nodes("state_machines")}
        labels = {}
        for sm in self.g.nodes("state_machines"):
            for s in sm["states"]:
                labels[s] = s.replace("_", " ").capitalize()
        content = f"""{HEADER}
import type {{ PermissionId }} from './permissions';

export interface Transition {{
  from: string;
  to: string;
  permission: PermissionId | null;
}}
export interface StateMachine {{
  entity: string;
  field: string;
  initial: string;
  states: readonly string[];
  transitions: readonly Transition[];
}}

export const STATE_MACHINES = {ts_json(machines)} as unknown as Record<string, StateMachine>;

export const STATE_LABELS: Record<string, string> = {ts_json(labels)};

export function stateLabel(state: string): string {{
  return STATE_LABELS[state] ?? state;
}}

/** Transitions the graph defines out of `from` that the current user is allowed to perform. */
export function allowedTransitions(machineId: string, from: string, isPermitted: (permission: PermissionId) => boolean): string[] {{
  const machine = STATE_MACHINES[machineId];
  if (!machine) return [];
  return machine.transitions.filter((t) => t.from === from && (t.permission === null || isPermitted(t.permission))).map((t) => t.to);
}}
"""
        self._emit("src/lib/stateMachines.ts", content, "State-machine tables from state_machines.json", list(machines))

    def _write_routes(self, specs: list[ScreenSpec]) -> None:
        login = next((s for s in specs if s.kind == "login"), None)
        login_wf = next((w for w in self.g.workflows if w["kind"] == "login"), None)
        home_screen = (login_wf or {}).get("success", {}).get("navigate")
        home = next((s for s in specs if s.screen_ref == home_screen), None) or next((s for s in specs if s.layout == "authenticated"), specs[0])
        routes = {s.screen_ref: s.route for s in specs}
        content = f"""{HEADER}
export const ROUTES = {ts_json(routes)} as const;
export type ScreenId = keyof typeof ROUTES;

export const LOGIN_ROUTE: string = '{login.route if login else '/login'}';
export const HOME_ROUTE: string = '{home.route}';

/** Build a concrete URL for a screen, substituting `:param` segments. */
export function routeTo(screen: ScreenId, params: Record<string, string> = {{}}): string {{
  return ROUTES[screen].replace(/:(\\w+)/g, (_m, key: string) => encodeURIComponent(params[key] ?? ''));
}}
"""
        self._emit("src/app/routes.ts", content, "Route table from screens.json", list(routes))
        nav = sorted((s for s in self.g.screens if s.get("nav")), key=lambda s: s.get("nav_order", 99))
        items = [{"label": s["name"], "to": s["route"], "permissions": s.get("permissions", [])} for s in nav]
        content = f"""{HEADER}
import type {{ PermissionId }} from '../lib/permissions';

export const APP_NAME = {json.dumps(self._project_node()['name'])};

export interface NavItem {{
  label: string;
  to: string;
  permissions: PermissionId[];
}}

export const NAV_ITEMS: NavItem[] = {ts_json(items)} as NavItem[];
"""
        self._emit("src/app/navigation.ts", content, "Navigation items from screens.json", [s["id"] for s in nav])
        imports, public_routes, auth_routes = [], [], []
        for s in specs:
            imp = import_path("src/app/router.tsx", s.page_path)
            imports.append(f"import {{ {s.page_component} }} from '{imp}';")
            perms = ", ".join(f"'{p}'" for p in s.permissions)
            el = f"<{s.page_component} />"
            if s.layout == "authenticated" and s.permissions:
                el = f"<RequirePermission permissions={{[{perms}]}}>{el}</RequirePermission>"
            entry = f"{{ path: '{s.route}', element: {el} }}"
            (auth_routes if s.layout == "authenticated" else public_routes).append(entry)
        content = f"""{HEADER}
import {{ Navigate, createBrowserRouter }} from 'react-router-dom';
import {{ RequireAuth }} from '../features/auth/RequireAuth';
import {{ RequirePermission }} from '../features/auth/RequirePermission';
import {{ AppLayout }} from '../layouts/AppLayout';
import {{ PublicLayout }} from '../layouts/PublicLayout';
{chr(10).join(imports)}
import {{ NotFoundPage }} from './NotFoundPage';
import {{ HOME_ROUTE }} from './routes';

/** One route per graph screen (screens.json); the router is regenerated, never hand-edited. */
export const router = createBrowserRouter([
  {{ path: '/', element: <Navigate to={{HOME_ROUTE}} replace /> }},
  {{ element: <PublicLayout />, children: [
    {(','+chr(10)+'    ').join(public_routes)},
  ] }},
  {{ element: <RequireAuth><AppLayout /></RequireAuth>, children: [
    {(','+chr(10)+'    ').join(auth_routes)},
  ] }},
  {{ path: '*', element: <NotFoundPage /> }},
], {{ future: {{ v7_relativeSplatPath: true, v7_fetcherPersist: true, v7_normalizeFormMethod: true, v7_partialHydration: true, v7_skipActionErrorRevalidation: true }} }});
"""
        self._emit("src/app/router.tsx", content, "React Router tree generated from screen specifications", [s.screen_ref for s in specs])

    def _write_e2e_data(self) -> None:
        seed = seed_data(self.g)
        user_col = collection_of(self.user_entity["id"]) if self.user_entity else "users"
        rp = {k: sorted(v) for k, v in role_permissions(self.g).items()}
        wf_by_api = {w["api"]: w for w in self.g.workflows}
        table = []
        for b in self.bindings:
            wf = wf_by_api.get(b.id, {})
            ent = b.entity_ref or b.request_entity_ref
            table.append({
                "id": b.id, "method": b.method, "path": b.path, "operation": b.operation, "auth": bool(b.api.get("auth", True)),
                "permission": b.api.get("permission"), "collection": collection_of(ent) if ent and b.operation != "login" else None,
                "idPrefix": slug(ent) if ent else "item", "machine": wf.get("state_machine"),
                "requestFields": [{"name": f["name"], "required": bool(f.get("required")), "source": f.get("source", "form")} for f in (b.api.get("request") or {}).get("fields", [])],
            })
        machines = {sm["id"]: {"collection": collection_of(sm["entity"]), "field": sm["field"], "initial": sm["initial"],
                               "transitions": [{"from": t["from"], "to": t["to"], "permission": t.get("permission")} for t in sm["transitions"]]}
                    for sm in self.g.nodes("state_machines")}
        content = f"""{HEADER}
export const SESSION_KEY = '{self.g.project_id}.session';
export const USER_COLLECTION = '{user_col}';

export const SEED: Record<string, Array<Record<string, unknown>>> = {ts_json(seed.collections)};

export const CREDENTIALS: Array<{{ email: string; password: string; user_id: string; role: string }}> = {ts_json(seed.credentials)};

export const ROLE_PERMISSIONS: Record<string, string[]> = {ts_json(rp)};

export const MACHINES: Record<string, {{ collection: string; field: string; initial: string; transitions: Array<{{ from: string; to: string; permission: string | null }}> }}> = {ts_json(machines)};

export const API_TABLE: Array<{{
  id: string; method: string; path: string; operation: string; auth: boolean; permission: string | null;
  collection: string | null; idPrefix: string; machine: string | null;
  requestFields: Array<{{ name: string; required: boolean; source: string }}>;
}}> = {ts_json(table)};
"""
        self._emit("tests/e2e/support/data.ts", content, "Mock-API data derived from api.json, entities and permissions", [b.id for b in self.bindings])
